### ISSUE TITLE
How to lable my own data?Just like the normal picture?

### ISSUE THREAD

**Issue by z6491679** [keevin60907/SpherePHD#4]
hi,I want to make my own dataset, but I found that the omi-mnist data is produced by mnist data, but my own data only have ERP pictures. How to label this type data?Can I lable my object just like the normal image object detection labeling?

**Comment by keevin60907** [comment]
I implement the transformation between ERP pictures and icosahedral representations and the convolution which is mentioned in the original paper.
The label example is based on segmentation tasks, and you can label other data by yourself.
